version: 2.1

jobs:
  build:
    docker: &docker
      -  image: circleci/node:13.8.0
    step:
    - checkout
    - run:
        npm run lint

  test:
    <<: *docker
    steps:
      - checkout
      - run:
          npm run test

  analyse:
    <<: *docker
    steps:
      - checkout
      - run:
          npm audit


workflows:
  my_workflow:
    jobs:
    - build
    - test:
        requirs:
          - build
    - analyse:
        requires:
          - test
